GET http://localhost:8080/users

###

POST http://localhost:8080/users
Content-Type: application/json

{
    "usernameOrEmail": "test",
    "password": "test"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json


###
POST http://localhost:8080/users/register
Content-Type: application/json

{
    "username": "test",
    "email": "test@test.com",
    "password": "testtest@T1"
}
###
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "usernameOrEmail": "65070051@kmitl.ac.th",
    "password": "croissantlover_123"
}

###
GET http://localhost:8080/users/getChar
Content-Type: application/json

###
GET http://localhost:8080/users/logout
Content-Type: application/json